/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        "outline": "#737686",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-container-high": "#e7e7f3",
        "secondary": "#712ae2",
        "background": "#faf8ff",
        "surface-container-highest": "#e1e2ed",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed": "#25005a",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "on-surface": "#191b23",
        "surface-container": "#ededf9",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-background": "#191b23",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2563eb",
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        "surface-bright": "#faf8ff",
        "primary": "#004ac6",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed": "#131b2e",
        "inverse-on-surface": "#f0f0fb",
        "tertiary": "#4d556b",
        "secondary-container": "#8a4cfc",
        "primary-fixed": "#dbe1ff",
        "inverse-primary": "#b4c5ff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#dae2fd",
        "on-tertiary": "#ffffff",
        "surface": "#faf8ff",
        "on-tertiary-container": "#eef0ff",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e2ed",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3039",
        "surface-dim": "#d9d9e5",
        "tertiary-container": "#656d84",
        "secondary-fixed": "#eaddff",
        "tertiary-fixed-dim": "#bec6e0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "xl": "32px",
        "gutter": "16px",
        "unit": "8px",
        "sm": "8px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "heading-xl": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "heading-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "button-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "heading-xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "heading-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "button-lg": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    }
  },
  plugins: []
}
